[project]
name = "easy-gaussian-process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pyro-ppl>=1.9.1",
    "scanpy>=1.11.4",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
